name = "loculate-proxy"
main = "src/index.js"
compatibility_date = "2024-02-20"

[vars]
# define API key here, inputted secretly with "wrangler secret put GOOGLE_MAPS_API_KEY"
GOOGLE_MAPS_API_KEY = ""

[observability.logs]
enabled = true
invocation_logs = false
head_sampling_rate = 0